/**
CREATE DATABASE IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4;
CREATE USER IF NOT EXISTS 'test_user'@'%' IDENTIFIED BY 't3stpa55';
GRANT ALL PRIVILEGES ON test.* TO 'test_user'@'%';
FLUSH PRIVILEGES;
USE `test`;
/**/

/**
-- SELECT @@SESSION.sql_mode;
--   ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
-- SET SESSION sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
/**/

/**
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS log;

DROP INDEX message_created_idx ON message;
DROP INDEX message_int_id_idx ON message;
DROP INDEX log_address_idx ON log;
/**/

CREATE TABLE IF NOT EXISTS message (
	created TIMESTAMP NOT NULL DEFAULT 0,
	id VARCHAR(255) NOT NULL,
	int_id CHAR(16) NOT NULL,
	str VARCHAR(1024) NOT NULL,
	status TINYINT(1),
	CONSTRAINT message_id_pk PRIMARY KEY(id)
);
CREATE INDEX message_created_idx ON message (created);
CREATE INDEX message_int_id_idx ON message (int_id);

CREATE TABLE IF NOT EXISTS log (
	created TIMESTAMP NOT NULL DEFAULT 0,
	int_id CHAR(16) NOT NULL,
	str VARCHAR(1024),
	address VARCHAR(255)
);
CREATE INDEX log_address_idx USING HASH ON log (address);
